# Generated by Django 4.2.6 on 2023-10-25 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_habit_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='продолжительность выполнения привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit_period',
            field=models.CharField(choices=[('ежечасно', 'ежечасно'), ('ежедневно', 'ежедневно'), ('еженедельно', 'еженедельно')], default='ежедневно', max_length=20, verbose_name='периодичность привычки'),
        ),
    ]
